# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev72+gb8518fc.d20230831'
__version_tuple__ = version_tuple = (0, 1, 'dev72', 'gb8518fc.d20230831')
